[package]
name = "vm-dyndns"
version = "0.1.0"
authors = ["Eric Ogren <eogren@linkedin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
